import "./globals.css";


export const metadata = {
  title: "Shared VR Stories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/wlm0ded.css"></link>
      </head>
      
      <body>
        {children}
      </body>
    </html>
  );
}